INSERT INTO turma VALUES (1, "SEGUNDA, TERÇA, QUARTA", "TURMA 1", "MANHÃ", 1);
INSERT INTO turma VALUES (2, "TERÇA, QUARTA, QUINTA", "TURMA 2", "TARDE", 1);
INSERT INTO turma VALUES (1, "QUARTA, QUINTA, SEXTA", "TURMA 3", "NOITE", 2);
INSERT INTO turma VALUES (1, "SEGUNDA, TERÇA, QUARTA", "TURMA 4", "MANHÃ", 2);
INSERT INTO turma VALUES (1, "TERÇA, QUARTA, QUINTA", "TURMA 5", "TARDE", 2);